[build]
  publish = "dist"
  command = "npm ci && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# SPA redirect - must come AFTER static file rules
[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# YAML files
[[headers]]
  for = "/*.yaml"
  [headers.values]
    Content-Type = "application/x-yaml"