navigation:
  - key: introduction
    children:
      - path: /
        key: introOverview
      - path: /intro/what-is-cli
        key: introWhatIs
      - path: /intro/why-cli
        key: introWhy
      - path: /intro/getting-started
        key: introGettingStarted
  
  - key: installation
    children:
      - path: /installation
        key: installOverview
      - path: /installation/requirements
        key: installRequirements
      - key: installDetail
        children:
          - path: /installation/detail/windows
            key: installWindows
          - path: /installation/detail/macos
            key: installMacos
          - path: /installation/detail/linux
            key: installLinux
      - path: /installation/model-config
        key: installModelConfig
      - path: /installation/knowledge-base
        key: installKnowledgeBase
      - path: /installation/verify
        key: installVerify
  
  - key: basicCommands
    children:
      - path: /basic-commands
        key: basicOverview
      - path: /basic/system-commands
        key: basicSystemCommands
      - path: /basic/dialog-commands
        key: basicDialogCommands
      - path: /basic/program-commands
        key: basicProgramCommands
  
  - key: advancedUsage
    children:
      - path: /advanced-usage
        key: advancedOverview
      - path: /advanced/scripting
        key: advancedScripting
      - path: /advanced/pipes
        key: advancedPipes
      - path: /advanced/regex
        key: advancedRegex
      - path: /advanced/automation
        key: advancedAutomation
  
  - key: troubleshooting
    children:
      - path: /troubleshooting
        key: troubleOverview
      - path: /trouble/common-errors
        key: troubleCommonErrors
      - path: /trouble/debugging
        key: troubleDebugging
      - path: /trouble/faq
        key: troubleFaq